# Generated by Django 4.1.4 on 2022-12-18 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio", models.FileField(upload_to="", verbose_name="audio file")),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="state name")),
                ("offset_time", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PrayerEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("after", "after"), ("before", "before")],
                        max_length=50,
                    ),
                ),
                ("repeated", models.BooleanField(default=True)),
                (
                    "prayer",
                    models.CharField(
                        choices=[
                            ("elfajer", "elfajer"),
                            ("duhr", "duhr"),
                            ("alasr", "alasr"),
                            ("almaghreb", "almaghreb"),
                            ("alaicha", "alaicha"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        blank=True, max_length=250, null=True, upload_to="prayer_event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prayer_time",
                    models.JSONField(
                        blank=True, null=True, verbose_name="prayer data time"
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="adan.state"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mosque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="name of mosque"),
                ),
                ("status", models.BooleanField(default=False)),
                ("prayer", models.JSONField(blank=True, null=True)),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adan.state",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
