# Generated by Django 4.1.4 on 2022-12-20 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("adan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrayerAudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio", models.FileField(upload_to="", verbose_name="audio file")),
                (
                    "prayer",
                    models.CharField(
                        choices=[
                            ("elfajer", "elfajer"),
                            ("duhr", "duhr"),
                            ("alasr", "alasr"),
                            ("almaghreb", "almaghreb"),
                            ("alaicha", "alaicha"),
                        ],
                        max_length=50,
                    ),
                ),
                ("audio_duration", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="mosque",
            old_name="user",
            new_name="topic",
        ),
        migrations.AddField(
            model_name="liveevent",
            name="audio_duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prayerevent",
            name="audio_duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=300, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
