# Generated by Django 4.1.4 on 2022-12-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adan", "0002_prayeraudio_rename_user_mosque_topic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="user",
        ),
        migrations.DeleteModel(
            name="Mosque",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
