# Generated by Django 4.1.4 on 2022-12-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adan", "0005_mosque_topic_liveevent_name_liveevent_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="liveevent",
            name="user",
        ),
        migrations.RemoveField(
            model_name="prayerevent",
            name="user",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="user",
        ),
    ]
