# Generated by Django 4.1.4 on 2022-12-31 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adan", "0006_remove_liveevent_user_remove_prayerevent_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mosque",
            name="state",
        ),
        migrations.RemoveField(
            model_name="mosque",
            name="topic",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
        migrations.DeleteModel(
            name="Mosque",
        ),
        migrations.DeleteModel(
            name="State",
        ),
    ]
