# Generated by Django 4.1.4 on 2023-01-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adan", "0007_remove_mosque_state_remove_mosque_topic_delete_topic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prayerevent",
            name="repeated",
        ),
        migrations.AddField(
            model_name="prayerevent",
            name="name",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
