# Generated by Django 4.1.4 on 2023-01-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adan", "0009_prayerevent_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liveevent",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
