# Generated by Django 4.1.4 on 2023-01-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adan", "0010_alter_liveevent_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liveevent",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="prayerevent",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
