# Generated by Django 4.1.4 on 2023-03-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adan", "0013_liveevent_downloaded_prayeraudio_downloaded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayerevent",
            name="scheduled",
            field=models.BooleanField(default=False),
        ),
    ]
