# Generated by Django 4.1.4 on 2022-12-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mqtt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="audio",
            field=models.CharField(max_length=150, verbose_name="Audio path"),
        ),
        migrations.AlterField(
            model_name="job",
            name="chron",
            field=models.CharField(max_length=150, verbose_name="Chron schedule"),
        ),
    ]
