"""
Django settings for el_moadin_pi project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from el_moadin_pi.utils import getserial, prayer_source
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-&eso57mwp7o#%@_6v%d=x2daozw!l*%d(3hxfc%45-atr*4p+("

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["localhost"]


# Application definition

INSTALLED_APPS = [
    'django_crontab',
    "mqtt",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "adan",
    'constance',
    'constance.backends.database',
    'background_task',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "el_moadin_pi.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "el_moadin_pi.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Algiers"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# constance settings

CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

CONSTANCE_ADDITIONAL_FIELDS = {
    'json_field': ['django.forms.JSONField', {}],
    'integer_field': ['django.forms.IntegerField', {}],
}

PRAYER_SOURCE = str(prayer_source)

CONSTANCE_CONFIG = {
    'PRAYER_SOURCE': (f"{PRAYER_SOURCE}",'Prayer source', 'json_field'),
    'PrayerTime': (f"{PRAYER_SOURCE}", 'Prayer', 'json_field'),
    'mosque': ("Mosque name", 'Name'),
    'elfajer': ("", 'Prayer hour'),
    'elfajer_schedul': (False, 'Prayer hour'),
    'duhr': ("", 'Prayer hour'),
    'duhr_schedul': (False, 'Prayer hour'),
    'alasr': ("", 'Prayer hour'),
    'alasr_schedul': (False, 'Prayer hour'),
    'almaghreb': ("", 'Prayer hour'),
    'almaghreb_schedul': (False, 'Prayer hour'),
    'alaicha': ("", 'Prayer hour'),
    'alaicha_schedul': (False, 'Prayer hour'),
    'offset_time': (0, 'Offset Time', "integer_field"),
    'broker_ip': ("142.44.163.144", 'Broker address'),
}

CONSTANCE_CONFIG_FIELDSETS = {
    'Prayer source Options': {
        'fields': ('PRAYER_SOURCE', 'PrayerTime'),
        'collapse': True
    },
    'Prayers ': ('elfajer','elfajer_schedul','duhr','duhr_schedul','alasr','alasr_schedul','almaghreb','almaghreb_schedul','alaicha','alaicha_schedul',),
    'Offset time config ': ('offset_time',) ,
    'Device settings': ('broker_ip', "mosque") ,
}

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# tasks settings

MAX_ATTEMPTS = 1
MAX_RUN_TIME = 0
# BACKGROUND_TASK_RUN_ASYNC = True

# CRONJOBS

CRONJOBS = [
    ('* * * * *', 'el_moadin_pi.cron.daily', '>> {}/cron.log'.format(BASE_DIR)),
]

SERIAL_NUMBER = getserial()
# SERIAL_NUMBER = "69335335"
# SERIAL_NUMBER = "72113824"
